# Generated by Django 5.0.7 on 2025-04-16 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company_category',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stremail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_city', to='myapp.city')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_state', to='myapp.state')),
            ],
            options={
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmpname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100, null=True)),
                ('noofvacancies', models.IntegerField()),
                ('requiredqualification', models.CharField(max_length=100)),
                ('requiredexperience', models.CharField(max_length=100)),
                ('jobdescription', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('applystartdate', models.DateField()),
                ('lastdate', models.DateField()),
                ('skillsrequired', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.agency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followid', models.CharField(max_length=100)),
                ('followdate', models.DateField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'db_table': 'followers',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('eemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applydate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='MemberEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passingyear', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'membereducation',
            },
        ),
        migrations.CreateModel(
            name='MemberExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=100)),
                ('worktitle', models.CharField(max_length=100)),
                ('workdetails', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('totalmonthexperience', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'memberexperience',
            },
        ),
        migrations.CreateModel(
            name='MemberLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'memberlanguage',
            },
        ),
        migrations.CreateModel(
            name='MemberLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_name', models.CharField(max_length=100)),
                ('link_url', models.URLField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'memberlink',
            },
        ),
        migrations.CreateModel(
            name='MemberSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'memberskills',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=100)),
                ('msgdt', models.DateField()),
                ('fromlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='myapp.login')),
                ('tologin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='myapp.login')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cmpname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('stremail', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('strmobileno', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, max_length=300, null=True)),
                ('overview', models.TextField(blank=True, max_length=500, null=True)),
                ('mission', models.TextField(blank=True, max_length=500, null=True)),
                ('vision', models.TextField(blank=True, max_length=500, null=True)),
                ('values', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10)),
                ('cmp_strength', models.IntegerField(blank=True, null=True)),
                ('ccid', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.companycategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.state')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization'),
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positionname', models.CharField(max_length=100)),
                ('companycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companycategory')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.positions'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posttitle', models.CharField(max_length=100)),
                ('postcontent', models.FileField(blank=True, null=True, upload_to='content/')),
                ('postdesc', models.TextField()),
                ('postdttime', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentsdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'cityname')},
        ),
    ]
