# Generated by Django 5.0.7 on 2025-04-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobdescription',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('login', 'post')},
        ),
    ]
