# Generated by Django 5.0.7 on 2025-04-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_job_jobdescription_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
    ]
