# Generated by Django 5.0.7 on 2025-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
