# Generated by Django 5.0.7 on 2025-04-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_likes_alter_likes_login_alter_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
