# Generated by Django 5.0.7 on 2025-04-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_likes_login_alter_likes_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.agency'),
        ),
    ]
