# Generated by Django 5.0.7 on 2025-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_organization_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='intro',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='overview',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
