# Generated by Django 5.1.7 on 2025-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_memberexperience_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberexperience',
            name='workdetails',
            field=models.TextField(),
        ),
    ]
