# Generated by Django 5.1.7 on 2025-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_memberexperience_workdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
